// app/layout.jsx
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";

// Font Google siap pakai
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "700"],
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
  weight: ["400", "700"],
});

// Metadata
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${robotoMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
